Add Podman-based container support

diff --git a/meta-oasis-vm/recipes-core/stage1-init/files/init b/meta-oasis-vm/recipes-core/stage1-init/files/init
--- a/meta-oasis-vm/recipes-core/stage1-init/files/init
+++ b/meta-oasis-vm/recipes-core/stage1-init/files/init
@@ -16,6 +16,9 @@ mount none -t devpts /dev/pts
 # in a different TD identity.
 stage2_root_hash=""
 stage2_hash_offset=""
+stage2_storage_mode=""
+stage2_storage_offset=""
+stage2_storage_size=""
 for cfg in $(cat /proc/cmdline | xargs -n1); do
 	case $cfg in
 		oasis.stage2.roothash=*)
@@ -25,6 +28,18 @@ for cfg in $(cat /proc/cmdline | xargs -n1); do
 		oasis.stage2.hash_offset=*)
 			# Stage 2 hash offset.
 			stage2_hash_offset="${cfg//oasis.stage2.hash_offset=}"
+		;;
+		oasis.stage2.storage_mode=*)
+			# Stage 2 ephemeral storage mode.
+			stage2_storage_mode="${cfg//oasis.stage2.storage_mode=}"
+		;;
+		oasis.stage2.storage_offset=*)
+			# Stage 2 storage space offset.
+			stage2_storage_offset="${cfg//oasis.stage2.storage_offset=}"
+		;;
+		oasis.stage2.storage_size=*)
+			# Stage 2 storage space size.
+			stage2_storage_size="${cfg//oasis.stage2.storage_size=}"
 		;;
 	esac
 done
@@ -44,7 +59,67 @@ veritysetup open \
 	/dev/vda \
 	${stage2_root_hash}
 
-# Mount stage 2 root filesystem and switch into it.
+# Mount stage 2 root filesystem (read-only).
 mkdir -p /stage2
 mount /dev/mapper/stage2 /stage2
+
+# When stage 2 storage filesystem offset is configured, set up read-write ephemeral storage.
+if [[ -n "${stage2_storage_mode}" && -d /stage2/storage ]]; then
+	echo "Using ephemeral storage mode: ${stage2_storage_mode}"
+
+	case $stage2_storage_mode in
+		disk)
+			if [[ -z "${stage2_storage_offset}" || -z "${stage2_storage_size}" ]]; then
+				echo "Missing disk-backed stage 2 ephemeral storage configuration."
+				exit 1
+			fi
+
+			# Generate a random key (this is ephemeral storage).
+			storage_key=$(dd if=/dev/urandom bs=1024 count=1 2>/dev/null | tr -dc 'a-zA-Z0-9' | dd bs=1 count=64 2>/dev/null)
+			# Format block device with dm-integrity and dm-crypt setup.
+			echo -n "${storage_key}" | cryptsetup luksFormat \
+				--offset ${stage2_storage_offset} \
+				--type luks2 \
+				--integrity hmac-sha256 \
+				--integrity-no-wipe \
+				/dev/vda
+			# Open block device.
+			echo -n "${storage_key}" | cryptsetup open \
+				--offset ${stage2_storage_offset} \
+				--type luks2 \
+				/dev/vda \
+				storage
+			# Create and mount filesystem.
+			mkfs.ext4 /dev/mapper/storage
+			mount /dev/mapper/storage /stage2/storage
+		;;
+		ram)
+			if [[ -z "${stage2_storage_size}" ]]; then
+				echo "Missing ram-backed stage 2 ephemeral storage configuration."
+				exit 1
+			fi
+
+			# Just use tmpfs.
+			mount none -t tmpfs -o size=${stage2_storage_size} /stage2/storage
+		;;
+		*)
+			echo "Unsupported stage 2 ephemeral storage mode."
+			exit 1
+		;;
+	esac
+
+	# Point /run to ephemeral storage if it exists.
+	if [ -d /stage2/run ]; then
+		mkdir /stage2/storage/run
+		mount --bind /stage2/storage/run /stage2/run
+	fi
+	# Point /var to ephemeral storage if it exists.
+	if [ -d /stage2/var ]; then
+		mkdir /stage2/storage/var
+		mkdir -p /stage2/storage/var/{lib,cache}
+		mount --bind /stage2/storage/var /stage2/var
+	fi
+fi
+
+# Switch into the new root.
 exec switch_root /stage2 /init
